In [12]:
def conversion_johnson2sdss(V, B_V, U_B, V_R, R_I):
    g = V + 0.63 * B_V - 0.124
    u = g + 0.75 * U_B + 0.77 * B_V + 0.72
    r = g - 1.646 * V_R + 0.139
    i = r - 1.007 * R_I + 0.236
    z = r - 1.584 * R_I + 0.386
    return u, g, r, i, z

In [13]:
u, g, r, i, z = conversion_johnson2sdss(15.256, 0.873, 0.320, 0.505, 0.511)

In [14]:
u, g, r, i, z

(17.3142,
 15.681989999999999,
 14.989759999999999,
 14.711183,
 14.566335999999998)

## They match pretty well, except small deviation in SDSS-r band.

In [2]:
from astropy.io import fits
from astropy.table import Table
import numpy as np

In [7]:
file = '/d/scratch/ASTR5160/data/legacysurvey/dr9/south/sweep/9.0/sweep-240p005-250p010.fits'
hdul = fits.open(file)
data = hdul[1].data
hdul.close()

In [40]:
mask = (248.858 < data['RA']) & (data['RA'] < 248.859) & (9.798 < data['DEC']) & (data['DEC'] < 9.799)
flux_z = data['FLUX_Z'][mask]
flux_g = data['FLUX_G'][mask]
flux_r = data['FLUX_R'][mask]

In [44]:
m_z = 22.5 - 2.5 * np.log10(flux_z)
m_g = 22.5 - 2.5 * np.log10(flux_g)
m_r = 22.5 - 2.5 * np.log10(flux_r)

In [45]:
m_z, m_g, m_r

(array([14.517736], dtype=float32),
 array([15.580078], dtype=float32),
 array([14.901785], dtype=float32))

In [46]:
data['FLUX_W1'][mask], data['FLUX_W2'][mask], data['FLUX_W3'][mask], data['FLUX_W4'][mask]

(array([603.8309], dtype=float32),
 array([328.57047], dtype=float32),
 array([38.98512], dtype=float32),
 array([-890.0304], dtype=float32))

## Flux in WISE is all very low, even negative at W4 band indicating no detection.